# Generated by Django 3.2.3 on 2021-06-02 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.usuario', verbose_name='Caja'),
            preserve_default=False,
        ),
    ]
