# Generated by Django 3.2.3 on 2021-05-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Categoria')),
                ('descripcionCategoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Descripcion de Categoria')),
            ],
            options={
                'verbose_name': 'Categoriaproducto',
                'verbose_name_plural': 'Categoriaproductos',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.IntegerField(verbose_name='Cantidad de Producto')),
                ('precioProducto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Detalle Producto',
                'verbose_name_plural': 'Detalle Productos',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlocal', models.IntegerField(blank=True, null=True, verbose_name='id Local')),
                ('dia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dia')),
                ('apertura', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apertura')),
                ('cierre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cierre')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcionProveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonoProveedor', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlocal', models.IntegerField(blank=True, null=True, verbose_name='Local')),
                ('nombreRepartidor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('carneRepartidor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Carne')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo Pago')),
            ],
            options={
                'verbose_name': 'TipoPago',
                'verbose_name_plural': 'TipoPagos',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apelUsuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('telUsuario', models.CharField(blank=True, max_length=8, null=True, verbose_name='Telefono')),
                ('direccionUsuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion')),
                ('estadoUsuario', models.IntegerField(blank=True, null=True, verbose_name='Estado')),
                ('emailUsuario', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('claveUsuari', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
